language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t gmlwo308/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true gmlwo308/react-test-app npm run test



after_success:
  - docker build -t gmlwo308/docker-frontend ./frontend
  - docker build -t gmlwo308/docker-backend ./backend
  - docker build -t gmlwo308/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push gmlwo308/docker-frontend
  - docker push gmlwo308/docker-backend
  - docker push gmlwo308/docker-nginx